name: my_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_face_detection: ^0.10.0
  camera: ^0.10.5
  shared_preferences: ^2.2.3
  csv: ^6.0.0
  path_provider: ^2.1.3
  share_plus: ^10.0.2
  permission_handler: ^11.3.1
  cross_file: ^0.3.4+2
  fl_chart: ^0.68.0
  open_file: ^3.3.2
  pdf: ^3.11.0
  printing: ^5.13.3
  supabase_flutter: ^2.10.3
  hive: ^2.2.3
  overlay_support: ^2.1.0
  image_picker: ^1.0.7
  intl: ^0.18.0
  tflite_flutter: ^0.10.4
  ffi: ^2.1.0
  image: ^4.0.17
  cupertino_icons: ^1.0.8
  logger: ^1.3.0
  flutter_image_compress: ^2.4.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/IDent_Logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/models/facenet.tflite
    - assets/images/IDent_Logo.png
